# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-18 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_auto_20180718_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='user_posted',
        ),
        migrations.AddField(
            model_name='message',
            name='user_dashboard',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_messages', to='user_app.User'),
            preserve_default=False,
        ),
    ]
